# Generated by Django 5.2.5 on 2025-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=15)),
                ("path", models.CharField(max_length=128)),
                ("username", models.CharField(blank=True, max_length=128)),
                ("status_code", models.IntegerField()),
            ],
        ),
    ]
