# Generated by Django 5.2.5 on 2025-08-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="accounts/profiles/avatars/"
            ),
        ),
    ]
