# Generated by Django 5.2.5 on 2025-08-21 07:14

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")

    users_without_profile = User.objects.filter(profile__isnull=True, is_active=True)

    new_profiles = [Profile(user=user) for user in users_without_profile]

    Profile.objects.bulk_create(new_profiles, batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_bio"),
    ]

    operations = [migrations.RunPython(create_profiles, migrations.RunPython.noop)]
